name = "test"
theme = "#36B9B9"
twitter = "invertaseio"
sidebar = [
  [ "Overview", "/" ],
  [ "Code and Focus", "/code-and-focus" ],
  [ "Code Links", "/code-links" ],
  [ "Comment Annotations", "/comment-annotations" ],
  [ "Filenames and Tabs", "/filenames-and-tabs" ],
  [ "Scrollycoding", "/scrollycoding" ],
  [ "Scrollycoding with Preview", "/scrollycoding-with-preview" ],
  [ "Spotlight", "/spotlight" ],
  [ "Spotlight with Preview", "/spotlight-with-preview" ]
]
googleTagManager = "GTM-W89J6BX"
experimentalCodehike = true
experimentalMath = true

[docsearch]
apiKey = "9b58d13ee3195094105d528fc6161a01"
indexName = "use_docs_page"
